### ISSUE TITLE
Annoying Warning: to-Python converter already registered [sf#1]

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo#1]
_Originally created by darioizzo on 2012-08-27 13:05:53._

When importing PyGMO (if also PyKEP is detected) the following is displayed:

RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored

**Comment by AmandaYingYiWu24** [comment]
I have read the article "Ubuntu Installation (step by step, including external libraries) --Guide for Ubuntu 14.04 with a 64 bit processor."
from Github website (https://github.com/tiangolo/caffe/blob/ubuntu-tutorial-b/docs/install_apt2.md).

    And now, I open IPython to test that PyCaffe is working. I input "ipython" command, and enter into the ipython page.

    Then, I input  the command "import caffe", but I got below warnings:
/root/code/caffe-master/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Net<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \

/root/code/caffe-master/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Blob<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \

/root/code/caffe-master/python/caffe/pycaffe.py:13: RuntimeWarning: to-Python converter for boost::shared_ptr<caffe::Solver<float> > already registered; second conversion method ignored.
  from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \

Would you pls help to give me some suggestions to resolve it?

**Comment by darioizzo** [comment]
This is not an issue with pagmo, maybe you may want to bring it to the attention of the pycaffe developers.
