### ISSUE TITLE
Multiple Boost versions installed and unable to locate the correct one

### ISSUE THREAD

**Issue by sriki18** [esa/pagmo#101]
Hi,

I have been trying over a day to install PyGMO now, but I haven't found a way yet. I will first provide the steps that I followed and then the issue that I am currently facing. I am running Ubuntu 14.04, and I will be happy to provide any other information required.

I downloaded boost source code (v. 1.57.0) from http://sourceforge.net/projects/boost/files/boost/1.57.0/ and saved it in /usr/local/ . On the terminal, I ran the following commands:

```
sudo tar zxf boost_1_57_0.tar.gz
sudo cd boost_1_57_0.tar.gz
sudo ./bootstrap.sh
sudo ./b2
```
This ran smoothly till 96%, and then produced a list of what I think are only warnings. (I also read at http://www.boost.org/doc/libs/1_57_0/more/getting_started/unix-variants.html , section 4.1, that some warnings shouldn't be a big deal). 

This had setup boost. I then ran the following at my ~/Desktop/dependencies/: 
```
git clone https://github.com/esa/pagmo.git
cd pagmo
mkdir build
cd build/
sudo ccmake ../
```
Now, I had to use sudo to detect boost properly, otherwise, even if I entered the correct path, it would not configure.

After configuring, I generate and exit. Now I run:
```
make
make install
ldconfig
python
from PyGMO import *
```
Now I get the following errors: 
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/usr/local/lib/python2.7/dist-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory
```

So I try to see what the problem is, and after much searching, tried this:
```
locate libboost_system
```
and got this:
```
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0
```

Now I know this means that there is some kind of version mismatch happening. I believe that boost 1.57 is not being detected. I did not install boost 1.54, it was there from the beginning. Before I change something that I can't unchange, I would like to know how to get the whole thing working

Also of note is that I have tried things in different directories (ran ./bootstrap.sh and ./b2 in different directories; also ran make and make install multiple times in different directories. I really hope this is not a big source of confusion.)

Any help would be appreciated. Please let me know if there is any other information required.

**Comment by darioizzo** [comment]
Hey,

you installed a new version of boost, pagmo finds it and links it in (for
some reason), but it is not located by the system wide library path ... you
have several options

1) Remove boost 1.57 (do you need it?)
2) Update LD_LIBRARY_PATH so that your system can locate the new boosts

Let us know,

Dario

**Comment by sriki18** [comment]
Hi,

So I did change LD_LIBRARY_PATH by running the following:

```
LD_LIBRARY_PATH="/usr/local/boost_1_57_0/"
```

So when I call 
``` 
$LD_LIBRARY_PATH
```
I get
```
bash: /usr/local/boost_1_57_0/: Is a directory
```

Am I doing this updation right? Even after doing this, I got the same error as last time. 

I would remove boost, but this felt like a shorter solution to the problem.

**Comment by darioizzo** [comment]
the sintax, I think, is

export LD_LIBRARY_PATH=/usr/local/boost_1_57_0/

check it though on linux forums (how to set an env variable) ....

Dario

**Comment by bluescarni** [comment]
@sriki18 any particular reason you are not using the standar ubuntu packages for boost?

**Comment by darioizzo** [comment]
I am going to close this one, if you have further questions @sriki18, please post them on our mailing-list.
