### ISSUE TITLE
Incorrect EdgeList container in pagmo::topology::base::graph_type ?

### ISSUE THREAD

**Issue by kiryx** [esa/pagmo#104]
The definition of adjacency_list used in topology is currently as follows:

```C++
typedef boost::adjacency_list<boost::vecS,boost::vecS,boost::bidirectionalS,boost::no_property,boost::property<boost::edge_weight_t,int>,boost::vecS> graph_type;
```
(also here: https://github.com/esa/pagmo/blob/master/src/topology/base.h#L84)

As I assume, the last template argument above (``boost::vecS``) was supposed to characterize the EdgeList container, as referenced here: http://www.boost.org/doc/libs/1_51_0/libs/graph/doc/adjacency_list.html (**Is this correct ?**)

If so, this is not what happens. Since only 6 template arguments are provided, the ``boost::vecS`` is instead characterizing the GraphProperty, while the EdgeList is set as ``boost::listS``(default). In order to fix it, an extra ``boost::no_property`` should be put right before the ``boost::vecS`` argument:

```C++
typedef boost::adjacency_list<boost::vecS,boost::vecS,boost::bidirectionalS,boost::no_property,boost::property<boost::edge_weight_t,int>,boost::no_property,boost::vecS> graph_type;
```

Once I applied this change I encountered a compilation error about ``boost::remove_edge`` and ``boost::clear_vertex`` not playing well with ``vecS`` as container for EdgeList:

```
/usr/include/boost/graph/detail/adjacency_list.hpp: In instantiation of ‘void boost::remove_edge(typename Config::vertex_descriptor, typename Config::vertex_descriptor, boost::bidirectional_graph_helper_with_property<Config>&) [with Config = boost::detail::adj_list_gen<boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, pagmo::topology::base::vertex_properties, pagmo::topology::base::edge_properties, pagmo::topology::base::graph_properties, boost::vecS>, boost::vecS, boost::vecS, boost::bidirectionalS, pagmo::topology::base::vertex_properties, pagmo::topology::base::edge_properties, pagmo::topology::base::graph_properties, boost::vecS>::config; typename Config::vertex_descriptor = long unsigned int]’:
/home/krzysztof/Projects/pagmo/src/topology/base.cpp:348:78:   required from here
/usr/include/boost/graph/detail/adjacency_list.hpp:1235:7: error: static assertion failed: (!is_same<EdgeListS, vecS>::value)
       BOOST_STATIC_ASSERT((!is_same<EdgeListS, vecS>::value));
```

So, **do we need ``vecS`` as a container for EdgeList ?**

1) I am making a series of changes to ``pagmo::topology::base`` class, and I will avoid fixing this and leave it as ``boost::listS`` for now (as it was all those years).
2) If you're fine with ``listS`` being a container for EdgeList, you can close this ticket, otherwise, I'd keep it for later improvement as a separate enhancement.

**Comment by darioizzo** [comment]
The commit dc1845f36249f1a52e059b5ba4c4374fa686b857 makes this question obsolete.
