### ISSUE TITLE
Setting archipelago.distribution_type by property does not work

### ISSUE THREAD

**Issue by kiryx** [esa/pagmo#108]
In PyGMO, the archipelago distribution type (broadcast, point_to_point) can be either set in constructor:

```Python
from PyGMO import archipelago, distribution_type

archi = archipelago(... , distribution_type=distribution_type.broadcast)
```
or as a property (at least there is interface for it!):

```Python
archi = archipelago(..)
archi.distribution_type = distribution_type.broadcast
```

The latter does not work, as the code always executes the point_to_point (default) distribution case.
**I haven't checked, but the same issue may occur for archipelago.migration_direction**

**Comment by jdiez17** [comment]
Looking into this, it seems like there is actually no property called "distribution_type" or "migration_direction" in PyGMO/core/core.cpp (The only property in that class is "topology"). Further, there doesn't appear to be a setter for either of these member variables in src/archipelago.h. 

Proposed fix:
* Add public getters and setters for distribution_type and migration_direction.
* Expose them through PyGMO. 
* Add tests in PyGMO and PaGMO.

Will send a PR tonight.

**Comment by kiryx** [comment]
Sorry, I think I made this ticket hastily... and now I think it's a non-issue.

I'm not sure if its safe to change the distribution type on the fly for instantiated archipelagos (**its definitely not safe and/or useful to change the migration_direction!**), so maybe those should not be interfaced in the first place, and just kept as parameters of constructor.

Don't work on it yet.

**Comment by jdiez17** [comment]
The copy and assignment operators seem to change these variables, but I'm not familiar enough with the code base to understand the implications of these. I'll wait for your green-light before committing any work.

**Comment by kiryx** [comment]
@jdiez17, If you're still interested in this ticket, you can in fact add the property for distribution_type (but **not** migration_direction) as you suggested before (getter/setter, expose to PyGMO and write unit test).

**Comment by jdiez17** [comment]
Got it. Expect a PR soon.
