### ISSUE TITLE
Help installing PyGMO

### ISSUE THREAD

**Issue by sriki18** [esa/pagmo#123]
I've been trying to install PyGMO on a Lubuntu 14.10 machine. 
After (apparently) successful steps that I followed listed on the Install page http://esa.github.io/pygmo/install.html , I am facing the following error:

```
>>> from PyGMO import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/usr/local/lib/python2.7/dist-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: libboost_system.so.1.57.0: cannot open shared object file: No such file or directory
```
Steps I followed

1. Download boost as a .tar.gz file.
2. Run <i>tar -zxf boost_1_57_0.tar.gz</i> which will create a folder called boost_1_57_0.
3. <i>cd boost_1_57_0/</i>
4. <i>./bootstrap.sh</i>
5. <i>./b2</i> (this runs for a while)
6. Download pagmo source. Make a new directory called build, move inside, run <i>ccmake ..</i>
7. Configure, but boost is not found. Boost_DIR, Boost_INCLUDE_DIR etc are all not found.
8. I make Boost_INCLUDE_DIR to point to the folder with boost. I am attaching a picture of CMake. It may be of note that Boost_DIR is still not found.
![temp3](https://cloud.githubusercontent.com/assets/7760814/6603925/0331195e-c84b-11e4-8668-404c2ca701fb.png)
​9. Configure twice, generate and exit.
10. <i>make</i>
11. <i>sudo make install</i>

12. <i>sudo ldconfig</i>
13. <i>python </i>
14. <i>from PyGMO import *</i>

Other things I tried

I tried finding all the libboost_system.so files.

```
codebox@codebox-VirtualBox:~/Desktop/pagmo/build$ locate libboost_system.so.
/home/codebox/Downloads/boost_1_57_0/bin.v2/libs/system/build/gcc-4.9.1/debug/threading-multi/libboost_system.so.1.57.0
/home/codebox/Downloads/boost_1_57_0/bin.v2/libs/system/build/gcc-4.9.1/release/threading-multi/libboost_system.so.1.57.0
/home/codebox/Downloads/boost_1_57_0/stage/lib/libboost_system.so.1.57.0
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.55.0
```
I figured this could mean there is another boost (v 1.55.0) which was already installed for some reason. Is it possible to point PyGMO to the correct boost (which is in /usr/Downloads/boost_1_57_0/ ) after installing it? As I did not install the 1.55.0 version, I do not know how to remove it.

**Comment by neduard** [comment]
Try `LD_LIBRARY_PATH`:
`LD_LIBRARY_PATH="/home/codebox/Downloads/boost_1_57_0/stage/lib/" python`

**Comment by sriki18** [comment]
This works! Thanks a lot!
