### ISSUE TITLE
Create test.h header file with utility debug functions

### ISSUE THREAD

**Issue by kiryx** [esa/pagmo#126]
In most C++ unit tests we redefine ``PRINT_VEC`` macro and ``is_eq`` function. Instead of redefining it, we should implement those in a header file and import them from the unit test (only for testing purposes and "pretty printing").

**Comment by AshishKhatkar** [comment]
@kiryx Is this still open? I saw test.h in tests folder. If it is still open want to contribute.

**Comment by kiryx** [comment]
Well, it just closed, sorry :)

**Comment by kiryx** [comment]
@AshishKhatkar, this solution is not ideal. I'm thinking about opening a larger ticket which aims at overhauling some of our C++ testcode (basically introducing "better" unit test macros, e.g. boost tests).

**Comment by AshishKhatkar** [comment]
@kiryx Right now nope. I just saw the issue but can give the code within 24 hours.
