### ISSUE TITLE
Integrate PaGMO with WORHP

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo#133]
In response to an ESA initiative in 2004 for developing a European NLP solver, the code WHORP was created and is available to academic institution and to ESA for free. The precompiled library and headers can be downloaded for different architecture from the site http://www.worhp.de/content/history

Like the SNOPT and IPOPT wrapper, PaGMO can wrap this solver, thus adding to its list of available optimizers.

I would then be very interested in running comparison to SNOPT and IPOPT on interplanetarey trajectory optimization.

**Comment by bluescarni** [comment]
Another example of code funded by public money and released under a restrictive non-free license. If you a re a taxpayer, you will have to pay twice for this. Depressing :(

**Comment by darioizzo** [comment]
Absolutely true!! They do provide the compiled binaries for free to most academic institutions and if you are a private citizen, but you still to be approved by them which beats the purpose ... :(

**Comment by bluescarni** [comment]
Right. And apparently even the academic license expires after 1 year.

**Comment by jhasse** [comment]
Hi!

I just saw this issue after opening #139. I've got a academic license for WORHP and am studying at the University of Bremen where WORHP is developed. I will ask what can be done for getting a license for pagmo developers, maybe limiting WORHP to smaller dimension (toy) problems if no license is found.

Btw: I'm working on a (very) small comparision of IPOPT and WORHP using the pagmo interface atm (don't have a license for SNOPT though).

**Comment by darioizzo** [comment]
:) thank, we do have licenses for worhp and were about to design the wrapper, but we will now take a look at your proposal and incorporate it as much as possible ..

**Comment by jhasse** [comment]
This can now be closed, right? :)

**Comment by darioizzo** [comment]
We still are developing WORHP support. Several things are to be tuned and tests performed ... we will close the ticket if the feature will no longer be just experimental.
