### ISSUE TITLE
QuickStart typo

### ISSUE THREAD

**Issue by manuelciosici** [esa/pagmo#143]
The QuickStart documentation at [1] consistently mentions that the algorithms evolve ten times over 200 generations while the code excerpt consistently evolves over 500 generations.

[1] https://esa.github.io/pygmo/quickstart.html

**Comment by kiryx** [comment]
This commit addresses the issue https://github.com/esa/pagmo/commit/955738caf222cabe70b59b81bd234bf41b69245c
