### ISSUE TITLE
Using multi-objective fitness functions with python 

### ISSUE THREAD

**Issue by elypma** [esa/pagmo#160]
When I try to use a multi-objective fitness function in python (returning a tuple with 2 values: (_value1, value2)) I get a c++ conversion error:

"""TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type tuple"""

I try to use the nspso algortihm.

**Comment by darioizzo** [comment]
you are probably having some syntax error. can you post the essential part of the code?

**Comment by elypma** [comment]
Thx for your quick response.
I indeed had a syntax error. It took me a while to figure out how to initialise a multi-objective problem.
I forgot to specify all the *args properly.

I am sorry to have bothered you with it.
I'll concentrate on further exploration.
