### ISSUE TITLE
Crash with combination of decompose and island (and a problem defined in python)

### ISSUE THREAD

**Issue by elypma** [esa/pagmo#161]
I try to extend the decompose example from the website to islands / archipelago and apply it to my own problem. I am running Anaconda v 2.3.0 64 bits on windows. in combination with PyGMO v1.1.5 (installed via conda).

As long as I stick to the example using the zdt(1,2) problem everything works. When I switch to my own problem (specified in python) the python kernel crashes when calling evolve.
Without islands both are running fine.

Here is my example.

``` python
from PyGMO import *
class MyProblem(problem.base):
    def __init__(self, *args, **kwargs):
        dim = 2
        n_obj = 2
        i_dim = 0
        super(MyProblem, self).__init__(dim, i_dim, n_obj)
        
    def _objfun_impl(self, x):
        _err1 = x[0]**2 + x[1]**2
        _err2 = x[0] - x[1]**2 + 10.2
        _crit = [_err1, _err2]
        return _crit 

_nGenerations = 50
_nPopulation = 20
_nEvolves = 10

#
# This doesn't work with an island (python crashes)
_myProblem = MyProblem(dim=2, n_obj=2)
#
# This does work
# _myProblem = problem.zdt(1,2)

_prob = problem.decompose(problem = _myProblem, weights = [0.5, 0.5])
_algo = algorithm.de_1220(gen=_nGenerations)
_isl = island(_algo,_prob,_nPopulation)

for i in xrange(_nEvolves):
    _isl.evolve(1);
    _isl.join()
    print "Generation ", i
    print "Decomposed fitness: " , _isl.population.champion.f
    print "Original fitness: " , _myProblem.objfun(_isl.population.champion.x)
    print "Solution: " , _isl.population.champion.x

**Comment by darioizzo** [comment]
This is a windows specific problem. In Windows it is not possible (or anyway risky) to define problems in python and use islands or archipelagos. This would infact trigger the use of the multiprocessing python module which has different behaviours in linux and windows.

You thus have two only options if you really need islands and archis

1) Use linux or a unix based system
2) Keep using windows 64, but define your problem in c++ and expose it to python (tutorial here https://github.com/esa/pagmo/wiki/%5BTUTORIAL%5D-Code-a-problem-in-Cpp,-use-it-in-Python)

**Comment by elypma** [comment]
Thx Dario.
Not really good news but I'll see what I can do.
Regards,
Egbert.



egbert

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=5.1.1&source=email_footer_2] On Tue, Oct 20, 2015 at 9:24 pm, Dario Izzo < notifications@github.com [notifications@github.com] > wrote:
This is a windows specific problem. In Windows it is not possible (or anyway
risky) to define problems in python and use islands or archipelagos. This would
infact trigger the use of the multiprocessing python module which has different
behaviours in linux and windows.

You thus have two only options if you really need islands and archis

1) Use linux or a unix based system
2) Keep using windows 64, but define your problem in c++ and expose it to python
(tutorial here 
https://github.com/esa/pagmo/wiki/%5BTUTORIAL%5D-Code-a-problem-in-Cpp,-use-it-in-Python
[https://github.com/esa/pagmo/wiki/%5BTUTORIAL%5D-Code-a-problem-in-Cpp,-use-it-in-Python] )

—
Reply to this email directly or view it on GitHub
[https://github.com/esa/pagmo/issues/161#issuecomment-149674905] .[https://github.com/notifications/beacon/ACEUiTrpt3DdxoFEtMGs68RdevVoCIfJks5o9oxhgaJpZM4GSa-Z.gif]
