### ISSUE TITLE
MPI Support in PyGMO

### ISSUE THREAD

**Issue by gnu-user** [esa/pagmo#163]
I've noticed that there is support for the C++ implementation for MPI, is there any possibility that support for MPI can be added to the Python binding in PyGMO?

There is currently support for MPI in python with mpi4py, are there any chances that support for MPI in PyGMO will be added in the future?

Thanks.

**Comment by darioizzo** [comment]
No, we are planning to add zeromq Islands .. But currently we have no developer working on it.
