### ISSUE TITLE
PyGMO-Anaconda Trouble  (Mac OS X 10.11.3)

### ISSUE THREAD

**Issue by GT-gradstudent** [esa/pagmo#169]
I am an engineering grad student, who has spent 4.5 days trying to get Anaconda to play nice with PyGMO on Mac OS X 10.11.3. 

**PAST SUCCESS INSTALLING PyGMO**
On this computer, I have been able to successfully build PyGMO and implement it within [Enthought Canopy](https://store.enthought.com/downloads/#default), which included successful builds of 3rd-party optimizers (ipopt, nlopt and gsl). Failed an attempt on integrating snopt, but w/e. I've since then completely removed all traces of Enthought Canopy, and the only remaining python on this computer (other than Anaconda root Py2.7) is the one that comes with OS X.

**CURRENT APPROACH**
After successfully executing the following steps, I get a successful PyGMO/pagmo build - in that - calling `$ make test` within `~/pagmo/build/` returns 15 out of 15 passed tests.
1. Successful install of [Anaconda](https://www.continuum.io)
2. Successful install of boost and [boost-python](https://anaconda.org/meznom/packages) using `conda install`
3. Successful build of PyGMO according to the PyGMO [website](http://esa.github.io/pygmo/install.html)

**THE ERROR**
Similar to what was reported [here](http://stackoverflow.com/questions/22575527/boost-python-python-linkage-error), I get the following report back after invoking: (1) `$ python -c 'import PyGMO'` in terminal or (2) `import PygMO` within scripts I call from Spyder: (similar to [#38](https://github.com/esa/pagmo/issues/38) ? )

```
$ python -c 'import PyGMO'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/John/anaconda/lib/python2.7/site-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/Users/John/anaconda/lib/python2.7/site-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: dlopen(/Users/John/anaconda/lib/python2.7/site-packages/PyGMO/core/_core.so, 2): Library not loaded: @rpath/./libboost_system.dylib
  Referenced from: /Users/John/anaconda/lib/python2.7/site-packages/PyGMO/core/_core.so
  Reason: image not found
```

**MY QUESTION(S)**
How to fix this and what is going on? (duh)
It's time for an expert. I know very little about things like symbolic linking so I'm hesitant to try things on my own like [these approaches](http://seite9.de/posts/anaconda.html), [writing dirty bash scripts](http://stackoverflow.com/questions/22575527/boost-python-python-linkage-error), or [linking against Anaconda on OS X](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/fUpqjkK5jEI).
- I think setting up boost and boost-python using the `conda build` would be preferable for me, but I'm not familiar with how to do this at this point - just started using Anaconda 4 days ago.
- Using a [Homebrew approach](http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/) to do a full boost install (`brew install boost --with-python27 --build-from-source`) is also something to try, and I did, but I'm worried that the previous command caused my brew to hang, as well similarly reported [here](http://superuser.com/questions/642113/brew-hanging-seemingly-frozen-when-installing-boost-for-nearly-an-hour). 

**MISCELLANEOUS**
**(1) `cmake ../` Report**
If I type `cmake ../` into the directory ~/pagmo/build, I get the following ...

```
$ cmake ../
-- OS detected: Darwin
-- CXX Compiler detected: Clang
-- CMake additional search path for libraries: /usr/local/lib
-- Enabling '-ftemplate-depth=256' compiler flag required since boost 1.54.
-- Enabling '-std=c++11' compiler flag
-- CXX compilation flags:  -ftemplate-depth=256 -Wno-deprecated-declarations -std=c++11
-- Python interpreter: /Users/John/anaconda/bin/python
-- Python interpreter verison: 2.7
-- Python includes path: /Users/John/anaconda/include/python2.7
-- Python modules install path: /Users/John/anaconda/lib/python2.7/site-packages
-- Python library name: /Users/John/anaconda/lib/libpython2.7.dylib
-- Required Boost libraries: system;serialization;thread;python
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   serialization
--   thread
--   python
-- Detected Boost version: 105700
-- Boost include dirs: /Users/John/anaconda/include
-- Boost libraries: /Users/John/anaconda/lib/libboost_system.dylib;/Users/John/anaconda/lib/libboost_serialization.dylib;/Users/John/anaconda/lib/libboost_thread.dylib;/Users/John/anaconda/lib/libboost_python-mt.dylib
-- Thread library: 
-- Build flags:  -ftemplate-depth=256 -Wno-deprecated-declarations -std=c++11 -DBOOST_THREAD_USE_DLL -DBOOST_SERIALIZATION_DYN_LINK=1
-- Module linker flags: 
-- Shared linker flags: 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/John/pagmo/build
```

**(2) `conda info` Report**
Downloaded Anaconda VERY recently...

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/John/anaconda  (writable)
  default environment : /Users/John/anaconda
     envs directories : /Users/John/anaconda/envs
        package cache : /Users/John/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**(3) `brew --config` Report**
Just in case, this is useful information (e.g. Xcode ver).

```
$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 51d5af08e29e7893b6978585a50664495b7c0d52
Last commit: 22 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11.3-x86_64
Xcode: 7.2.1
CLT: N/A
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /Users/John/anaconda/bin/python => /Users/John/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_40
```

**P.S.**
- In a previous (failed) effort to get PyGMO and Anaconda to play nice, I have also tried setting up boost and boost-python using homebrew according to [here](http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/), but I was getting a sig11 similar to what was reported [here](https://github.com/esa/pagmo/issues/38). I have since removed these 'bottles' using `brew uninstall`.

THANKS FOR YOUR HELP!!!

**Comment by pipete40** [comment]
I have not been able to install pygmo - anaconda in MacOSx either. It works great in linux

**Comment by darioizzo** [comment]
pagmo 1.x is not supported anymore. Try pagmo2, it has built in conda packages also for osx.

**Comment by oguerrer** [comment]
Hello,

Was there a definite solution to this issue. I have the same exact problem. I have compiled and installed PyGMO correctly by specifying the correct paths for python and boost from my anaconda installation. Everything installs smoothly but when I want to import PyGMO I get exactly the same error:

`>>> from PyGMO import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../anaconda/lib/python3.6/site-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/Users/.../anaconda/lib/python3.6/site-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: dlopen(/Users/.../anaconda/lib/python3.6/site-packages/PyGMO/core/_core.so, 2): Library not loaded: libpagmo.dylib
  Referenced from: /Users/.../anaconda/lib/python3.6/site-packages/PyGMO/core/_core.so
  Reason: image not found`

I would really appreciate any help to make this work.

**Comment by oguerrer** [comment]
Hello, I just found what was wrong. I had set the CMAKE_INSTALL_PREFIX to be the anaconda directory. I put is back to usr/local and now it works fine. There are probably other dependencies that are not in the anaconda path that needed to be found.

**Comment by darioizzo** [comment]
pygmo is no longer supported, please consider moving to pygmo2 (already in conda no need do compile and install).

**Comment by oguerrer** [comment]
Thanks a lot! I can't believe I did not see version 2.7. I think the most popular result is still version 1.

Great work thanks!
