### ISSUE TITLE
I can't find anywhere in the docs what is the chromosome representation and what are the genetic operators

### ISSUE THREAD

**Issue by NawfelBgh** [esa/pagmo#171]
I can't find anywhere in the docs:

* What is the chromosome representation and
* What are the genetic operators used for mutation and crossover.

**Comment by darioizzo** [comment]
I can't find anywhere in the docs:

What is the chromosome representation -> http://esa.github.io/pagmo/
What are the genetic operators used for mutation and crossover. -> Depends on the algorithm http://esa.github.io/pagmo/namespacepagmo_1_1algorithm.html

**Comment by NawfelBgh** [comment]
Thanks for the response

> What is the chromosome representation -> http://esa.github.io/pagmo/

I don't get what you mean, where in that page is the chromosome representation mentioned.

> the genetic operators used for mutation and crossover. -> Depends on the algorithm http://esa.github.io/pagmo/namespacepagmo_1_1algorithm.html

Let's take a concrete example, [goto SPEA2 page](http://esa.github.io/pagmo/classpagmo_1_1algorithm_1_1spea2.html) and `Ctrl+F` for "crossover". All you will get is:

> [in]	cr	Crossover probability
> [in]	eta_c	Distribution index for crossover 

What is the crossover operator your implementation of SPEA2 use?

Thank you again.

**Comment by darioizzo** [comment]
The chromosome representation is described in mathematical formalism as: find: x in R^n \times R^m. This implies the chromosome is made by n floats and n integers

For pagmo::algorithm::SPEA2, the genetic operators used are those used in the algorithm SPEA2 as described in the literature. You can also find it in the actual code here (https://esa.github.io/pagmo/spea2_8cpp_source.html) line 451 (SBX crossover)

**Comment by darioizzo** [comment]
The chromosome representation is described in mathematical formalism as: find: x in R^n \times N^m. This implies the chromosome is made by n floats and m integers

For pagmo::algorithm::SPEA2, the genetic operators used are those used in the algorithm SPEA2 as described in the literature. You can also find it in the actual code here (https://esa.github.io/pagmo/spea2_8cpp_source.html) line 451 (SBX crossover)

**Comment by NawfelBgh** [comment]
Thanks again.
