### ISSUE TITLE
Racing data

### ISSUE THREAD

**Issue by chrislovecnm** [esa/pagmo#172]
Love the racing components that your project has! I am looking to break down a race into data points not just a winner.  The goal is to generate race data in order to show progress by time. I understand that this will be quite a bit of data, which frankly is what we want.

**Comment by darioizzo** [comment]
Thanks!! Racing is a very nice component indeed ..... Good luck with your task, let us know if successful :)

**Comment by chrislovecnm** [comment]
@darioizzo sorry I was tired with a put that in ... and did not ask a question 😄 

I assume that https://github.com/esa/pagmo/blob/master/src/util/race_pop.cpp#L391 is showing the current rank of the racers during the race.  I need all of the ranks.  Would you save the data that is being logged to a vector?  Need to pass that back to python.

Next question, since you guys understand this math A TON more than me.  Is there anything out there that would show distance between neighbors?  We can fudge it, but I like to reuse code from people that actually understand the math better than me.

Thanks ... sorry I did not ask my damn question.
