### ISSUE TITLE
Racing Data

### ISSUE THREAD

**Issue by chrislovecnm** [esa/pagmo#173]
Sorry about the precious issue, figured out that I did not ask the darn question.

I assume that https://github.com/esa/pagmo/blob/master/src/util/race_pop.cpp#L391 is showing the current rank of the racers during the race. I need all of the ranks. Would you save the data that is being logged to a vector and then pass it back in a tuple?

Next question, since you guys understand this math A TON more than me. Is there anything out there that would show distance between neighbors? We can fudge it, but I like to reuse code from people that actually understand the math better than me.

**Comment by darioizzo** [comment]
Chris, we are not developing PaGMO v1.4 any more and will thus not make any further relase. We are currently working on PaGMO v2.0 and the racing routines will indeed be all restructured.

As per your second question, I am not sure what is intended by distance beteen neighbours as you are not providing us with any context. There is this code here, though: https://github.com/esa/pagmo/blob/master/src/util/neighbourhood.h which may be relevant?
