### ISSUE TITLE
Undefined boost symbol error on importing PyGMO

### ISSUE THREAD

**Issue by akshayc11** [esa/pagmo#175]
Hi,
I installed PyGMO based on the instructions and images in the PyGMO installation guide (The main changes to default was--> Build main: NO Build PyGMO: yes), and the solution (1) for issue 
#149 

The installation completed with no error, however, after performing ldconfig and then trying to import PyGMO, I get the following:

```
import PyGMO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/PyGMO/__init__.py", line 57, in <module>
    from PyGMO import core, algorithm, migration, problem, topology, test, util
  File "/usr/lib/python2.7/dist-packages/PyGMO/core/__init__.py", line 2, in <module>
    from PyGMO.core._core import *
ImportError: /usr/local/lib/libpagmo.so: undefined symbol: _ZN5boost7archive17archive_exceptionC1ERKS1_

```

This seems to be some form of linking issue similar to http://stackoverflow.com/questions/11643666/python-importerror-undefined-symbol-for-custom-c-module

However, I am not sure what to change to fix this.

Thanks

Akshay

**Comment by darioizzo** [comment]
This is the same source of error as #174, just showing up in python at runtime rather than at compile time when building the static library.
