### ISSUE TITLE
Serialize PyGMO states for multi-session compute

### ISSUE THREAD

**Issue by arita37** [esa/pagmo#183]
Hello,

Just wondering if there is a way to do a multi-session batch job (with pause in the middle),
by serializing some states of the computation ?

It would be helpful when you have very large optimization spanning over days....

Thanks

**Comment by darioizzo** [comment]
The object archi can be serialized. So if you edd to archi.evolve(1000) you can archi.evolve(10) 100 times and serialize something like:
```
for i in range(100):
      archi.evolve(10)
      archi.join()
      SERIALIZE
```

**Comment by arita37** [comment]
Hi,

Thanks.
Does Pickle serialize works on this ?

Kind regards

**Comment by darioizzo** [comment]
It should yes ... if not your problem may have some rework to do (like if you use strange data members)
