### ISSUE TITLE
[Errno 32] Broken pipe Exception in PYGMO

### ISSUE THREAD

**Issue by arita37** [esa/pagmo#184]
Hi,

When running   
```
initpopulation= 200
archi = pyg.archipelago(topology=pyg.topology.fully_connected())
for i in range(0,nbprocess):
 isl= pyg.island(algo[i],prob, initpopulation)
 archi.push_back(copy.deepcopy(isl))
```
everything is fine.

but, when running
`isl.evolve(20)  # `

we receive the message:
```
Exception caught during evolution:In [33]: 
[Errno 32] Broken pipe
```
Does somebody has an idea how we can try to fix it ?
Thanks very much

**Comment by darioizzo** [comment]
What is are u using and what prob (Python or c++)?

**Comment by arita37** [comment]
Hello,
Thanks for your reply.
Am using Python 2.7  pygmo 1.1.5

Problem is:
```
class problem1(pyg.problem.base):     
    def __init__(self, dim=100):
        super(problem1,self).__init__(dim)

        lbound= list([ x[0] for x in bounds ])
        ubound= list([ x[1] for x in bounds ])
        self.set_bounds(lbound, ubound)

    def _objfun_impl(self, x):
        x= np.array(x, dtype=np.float)
        f= pf3.calc_obj(x)
        return (f, )

    def human_readable_extra(self):
        return "\n\t Problem dimension: " + str(self.__dim)

prob= problem1( len(bounds))
```

pf3 is a simple class,   method calc_obj(x) gives a real number (to be minimized).
Class pf3 just wraps data + method to make it easier, this is not a complicated class, no inheritance.

Thanks for your help.

**Comment by darioizzo** [comment]
Sorry I typed from my phone, I mean what OS (not is) ... :) Are you using windows?

**Comment by arita37** [comment]
Hi,
Config:
Pthon 2.7, Win 64bits, Anaconda.

If I just put 
f= np.sum(x*x-5)

It works well, it seems Object passing has some issues when passing to the dll binding.


Thanks for your help.


On 25 Aug 2016, at 16:18, Dario Izzo <notifications@github.com> wrote:

Sorry I typed from my phone, I mean what OS (not is) ... :) Are you using windows?

―

**Comment by arita37** [comment]
Do we need to overload elvove method in Pthon ?
I see this in the C++ Wrapper :

```
		void evolve(population &p) const
		{
			p = py_evolve(p);
		}
		// Changed implementations from Python.
		population py_evolve(const population &p) const
		{
			if (boost::python::override f = this->get_override("evolve")) {
				const population retval = f(p);
				return retval;
			}
			pagmo_throw(not_implemented_error,"the __evolve__() method has not been implemented");
		}
```

**Comment by darioizzo** [comment]
Indeed. I think the problem you are hitting is of a  fundamental nature ....
In windows you cannot use archis or islands to evolve populations if your problem is defined in pure python (as opposed to define a problem in c++ and expose it to python). So you have some options to do what you want:

1 - use algo.evolve()
2 - go to linux (recommended)
3 - wait for this to be fixed in pagmo 2.0 (will take a while though before we are able to release it)
4 - define your problem in c++ and expose it to python

Dario

**Comment by arita37** [comment]
Hi,

If we put the definition of problem in another module so multi processing can pick ?

1) Seems if we do
algo.evolve(5)
we have error... Of missing argument

Which parameter should we put ?


2) data are in python and not so easily tranposable in C++ (data are very large).....





On 25 Aug 2016, at 18:22, Dario Izzo <notifications@github.com> wrote:

Indeed. I think the problem you are hitting is of a fundamental nature ....
In windows you cannot use archis or islands to evolve populations if your problem is defined in pure python (as opposed to define a problem in c++ and expose it to python). So you have some options to do what you want:

1 - use algo.evolve()
2 - go to linux (recommended)
3 - wait for this to be fixed in pagmo 2.0 (will take a while though before we are able to release it)
4 - define your problem in c++ and expose it to python

Dario

―

**Comment by darioizzo** [comment]
Indeed its algo.evolve()

**Comment by arita37** [comment]
Hello,

When running on Linux, Python 2.7,  I have this error:
initpopulation= 20
archi = pyg.archipelago(topology=pyg.topology.ring())
for i in range(0,nbprocess):
  archi.push_back(pyg.island(algo[i],prob, initpopulation))


Traceback (most recent call last):

   File "<ipython-input-5-e8102a0add0a>", line 4, in <module>
     archi.push_back(pyg.island(algo[i],prob, initpopulation))

   File 
"/home/linux1/anaconda2/lib/python2.7/site-packages/PyGMO/core/__init__.py", 
line 55, in __get_deepcopy__
     return deepcopy(self)

   File "/home/linux1/anaconda2/lib/python2.7/copy.py", line 190, in 
deepcopy
     y = _reconstruct(x, rv, 1, memo)

   File "/home/linux1/anaconda2/lib/python2.7/copy.py", line 336, in 
_reconstruct
     y.__setstate__(state)

RuntimeError: unregistered void cast 
N5pagmo9algorithm2deE<-N5pagmo9migration13base_s_policyE


Where it comes from ?
Thanks


> Dario Izzo <mailto:notifications@github.com>
> Friday, August 26, 2016 3:54 PM
> Indeed its algo.evolve()
>

**Comment by darioizzo** [comment]
My guess is on a bad installation / linking to boost libraries.
Not sure I can help, but you may post the output of your cmake

**Comment by arita37** [comment]
But, If I used one of the pre-built problem, archipelago works well.
Believe it might related to a missing method in the problem definition ?

Boost is 1.5

Thanks

**Comment by darioizzo** [comment]
Boost version cannot be correct. You meant 1.57.0?
In any case, if you produce a minimal non working code I can try to see whats wrong ...

**Comment by arita37** [comment]
yes, 1.57.0
Sure, this example:


```
#Case 1: Using Pre-Built model, everything works.
prob= pyg.problem.schwefel(dim = 5)


#Case 2: Own problem
class my_problem(pyg.problem.base):
    def __init__(self, dim=10):
        super(my_problem,self).__init__(dim)
        self.set_bounds(-5.12, 5.12)

    #Objective function.
    def _objfun_impl(self, x):
        f = sum([x[i] * x[i] - x[i] for i in range(self.dimension)])
        return (f, )

    def human_readable_extra(self):
        return "\n\t Problem dimension: " + str(self.__dim)

prob = my_problem(dim=5)  

nbprocess= 2; nalgo= nbprocess
algo = []
for i in range(1, nalgo+1):
 algo.append(pyg.algorithm.de(gen=5,variant=i))

initpopulation= 30
archi = pyg.archipelago(topology=pyg.topology.ring())


#Add islant :  Error message ----------------------------
for i in range(0,nbprocess):
 archi.push_back(pyg.island(algo[i],prob, initpopulation))


#Error message is   :   
Traceback (most recent call last):

  File "<ipython-input-4-633d6d39e7c9>", line 2, in <module>
    archi.push_back(pyg.island(algo[i],prob, initpopulation))

  File "/home/linux1/anaconda2/lib/python2.7/site-packages/PyGMO/core/__init__.py", line 55, in __get_deepcopy__
    return deepcopy(self)

  File "/home/linux1/anaconda2/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)

  File "/home/linux1/anaconda2/lib/python2.7/copy.py", line 336, in _reconstruct
    y.__setstate__(state)

RuntimeError: unregistered void cast N5pagmo9algorithm2deE<-N5pagmo9migration13base_s_policyE


```

Thanks for your feedback.

**Comment by darioizzo** [comment]
you forgot dim and import .. can you try this (works on our systems in linux)

```python
import PyGMO as pyg

#Case 1: Using Pre-Built model, everything works.
prob= pyg.problem.schwefel(dim = 5)


#Case 2: Own problem
class my_problem(pyg.problem.base):
    def __init__(self, dim=10):
        super(my_problem,self).__init__(dim)
        self.set_bounds(-5.12, 5.12)
        self.__dim = dim

    #Objective function.
    def _objfun_impl(self, x):
        f = sum([x[i] * x[i] - x[i] for i in range(self.dimension)])
        return (f, )

    def human_readable_extra(self):
        return "\n\t Problem dimension: " + str(self.__dim)

prob = my_problem(dim=5)

nbprocess= 2; nalgo= nbprocess
algo = []
for i in range(1, nalgo+1):
 algo.append(pyg.algorithm.de(gen=5,variant=i))

initpopulation= 30
archi = pyg.archipelago(topology=pyg.topology.ring())


#Add islant :  Error message ----------------------------
for i in range(0,nbprocess):
 archi.push_back(pyg.island(algo[i],prob, initpopulation))
```

**Comment by arita37** [comment]
Case 1: Ok, works well.
Case 2: inser    self.__dim = dim  I have this error
`RuntimeError: unregistered void cast N5pagmo9algorithm2deE<-N5pagmo9migration13base_s_policyE
`
It looks like a method is missing when archi is adding an island to his list.

`base_s_policyE`

**Comment by darioizzo** [comment]
The code works fine here on our servers. Gentoo, archlinux and ubuntu based.
So I still think there is some problem with installation / compilation. If you post here the output from cMake I can try to diagnose this better.

**Comment by arita37** [comment]
Which version of PAGMO, Boost do you have ?

Details of the compil env are:
PAGMO is 1.1.5
boost-1.57.0-0
libgcc-4.8.2-0
openssl-1.0.1h-1
python-2.7.8-1
readline-6.2-2
sqlite-3.8.4.1-0
system-5.8-1
tk-8.5.15-0
zlib-1.2.7-0


Attached cnda recipe
https://drive.google.com/folderview?id=0B0YzHEQ2aKc0LVMtZC1kX1FkRFE&usp=sharing

**Comment by darioizzo** [comment]
You have a quite old system, but that should not be a problem as we used pagmo on older ones too. At the moment we use

gcc -> 6.1.1
boost -> 1.60.0
python -> 3.5

We do not use anaconda, but the standard linux toolchain, so the problem may be in they way the conda receipe does things ....

FYI, the cmake output in a working system looks like:

```cmake
-- OS detected: Linux
-- CXX Compiler detected: GNU
-- CMake additional search path for libraries: 
-- Enabling '-Wall' compiler flag.
-- Enabling '-Wno-deprecated' compiler flag.
-- Enabling '-Wextra' compiler flag.
-- Enabling '-Wnoexcept' compiler flag.
-- Enabling '-Wdisabled-optimization' compiler flag.
-- Enabling '-ffast-math' compiler flag.
-- Enabling '-std=c++11' compiler flag
-- CXX compilation flags:  -Wall -Wno-deprecated -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11
-- Required Boost libraries: system;serialization;thread;date_time
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
--   serialization
--   thread
--   date_time
--   chrono
--   atomic
-- Detected Boost version: 106000
-- Boost include dirs: /usr/include
-- Boost libraries: /usr/lib64/libboost_system.so;/usr/lib64/libboost_serialization.so;/usr/lib64/libboost_thread.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_chrono.so;/usr/lib64/libboost_atomic.so
-- Keplerian Toolbox library: /usr/local/lib/libkeplerian_toolbox.so
-- Keplerian Toolbox include dir: /usr/local/include
-- Thread library: -lpthread
-- MPI libraries: /usr/lib64/openmpi/libmpi_cxx.so;/usr/lib64/openmpi/libmpi.so
-- MPI include path: /usr/include
-- MPI compile flags: 
-- MPI link flags:  -Wl,-rpath  -Wl,/usr/lib/openmpi  -Wl,--enable-new-dtags
-- MPI exec file: /usr/bin/mpiexec
-- MPI exec num_processors flag: -np
-- MPI exec pre flags: 
-- MPI exec post flags: 
-- GSL library: /usr/lib64/libgsl.so
-- GSL CBLAS library: /usr/lib64/libgslcblas.so
-- GSL include dir: /usr/include
-- Running the GSL version checker.
-- GSL version checker output: 
	Detected GSL version: 2.1
-- GSL version is fine.
-- Found GSL BLAS library, linking it in.
-- NLopt library: /usr/lib64/libnlopt.so
-- NLopt include dir: /usr/include
-- BLAS support was requested, identifying system BLAS libraries.
-- A library with BLAS API found.
-- BLAS libraries: /usr/lib64/libblas.so
-- BLAS linker flags: 
-- snopt library: /usr/local/lib/libsnopt.so
-- snprint library: /usr/local/lib/libsnprint.so
-- f2c library: /usr/local/lib/libf2c.so
-- gfortran library: /usr/lib64/libgfortran.so
-- WORHP library: /usr/local/lib/libworhp.so
-- WORHP include dir: /usr/local/include
-- Build flags:  -Wall -Wno-deprecated -Wextra -Wnoexcept -Wdisabled-optimization -ffast-math -std=c++11 -pthread  -DBOOST_THREAD_USE_DLL -DBOOST_SERIALIZATION_DYN_LINK=1
-- Module linker flags:  
-- Shared linker flags:  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dario/Documents/pagmo/build
```

**Comment by arita37** [comment]
Is your PAGMO version 1.1.6 or 1.1.5 ?

It sounds related to DE migration base class binding....

How the python class problem is transposed into C++ in PAGMO ?

In the C++ version of  schwefel::schwefel, only objective function is define,....
https://github.com/esa/pagmo/blob/afbd72f880cbe08a7db1cb78ae49187aab862b9f/src/problem/schwefel.cpp

**Comment by darioizzo** [comment]
We use the latest PaGMO, the latest snapshot from the github repository, so it 1.1.8dev I guess ....

A python problem is "transposed" into c++ via https://github.com/esa/pagmo/blob/master/PyGMO/problem/python_base.h
and some more trickeries, I would not reccomend you to look into this as far as you are not an expert in c++, python and programming.

**Comment by arita37** [comment]
Think the problem comes between PAGMO 1.1.5(used here) and 1.1.8 (your side), 
on the binding of python class/method into C++ through Boost::Python class.

Is there a way to compare the changes between C++ 1.1.5 and 1.1.8 ?

When doing the deepcopy,  migration state/method is not available in the island.
Think there is an issue between base island and island model.

```
Here, constructor of base island:

		explicit base_island(const algorithm::base &, const population &,
			const migration::base_s_policy &,
			const migration::base_r_policy &);


```

**Comment by darioizzo** [comment]
I do not recall any changes on that part of the code between these versions, but you can always compare changes via git (https://github.com/esa/pagmo/compare/469aeef...master). There is a long list there. You can then navigate to the files you care about .....

**Comment by arita37** [comment]
So, do you an idea why it shows migration base policy when doing the deepcopy ? 

RuntimeError: unregistered void cast N5pagmo9algorithm2deE<-N5pagmo9migration13base_s_policyE

**Comment by darioizzo** [comment]
That is an error that is likely linked to object serialization. 
My guess is that PaGMO was wrongly compile/linked to boost libraries. But with no further information on how PAGMO was compiled I cannot really diagnose it.

**Comment by arita37** [comment]
Thanks for your view.

Can it be related to the gcc version when compiled and other  python 
package (like numpy),
creating a linking issue with gcc ?

http://stackoverflow.com/questions/11228941/python-embedding

Which gcc do you use for compiling ?

Sometimes, we spend much more solving "compil" and "platform 
dependance", "command line arguments" than
solving the core of our scientific problems, sometimes written in 
Japanese or in French/Italian....

Thanks, regards

**Comment by darioizzo** [comment]
I completely agree with you on your last statement .... 

If you really want to diagnose this problem, the only way I can help is by looking at the output of the cmake command. 
As I understand, you built PaGMO using some conda recipe, the problem lies (most likely) on this conda recipe and on how it builds PaGMO. Who gave you the recipe?
 
Would it be ok for you to just build it  from command line instead? That way we can follow the process step by step. If you have access to a linux system this would be rather straight forward. You would only need a gcc (latest version is ok, previous version also are ok as far as c++11 is supported), git and boost which are typically provided by all package managers.

The way to build pagmo is:

1) clone the latest git snapshot (git clone https://github.com/esa/pagmo.git)
2) make a dir called build in the pagmo folder
3) go in the directory build/ and type ccmake ../
4) select the requested build options from the ccmake interactive interface. i.e. select PyGMO
press c (configure), now write the conda python interpreter location in the PYTHON_EXECUTABLE variable. After pressing c again all libraries, headers and target dir will be automatically detected.
5) Press g (generate)
6) Back to the command line: make install

can you do this? 

Another option is to not use PaGMO ... are you sure you need PaGMO / PyGMO?

Dario
