### ISSUE TITLE
Save and resume in pagmo

### ISSUE THREAD

**Issue by jteuber** [esa/pagmo#189]
Hi,
I just had my optimizer crash on me after almost one day of runtime, probably a bug in my problem, but difficult to reproduce. I don't use archipelagos because the problem itself is multi-threaded. Now my question is, is it possible to export the current state of the population to a file and, after a crash, restore the population from this file and resume at that last point? (I'm working with the C++ API)
I couldn't find anything regarding this in the wiki or the docs. There doesn't even seem to be a method to initialize a population with given values.
Thanks for your help!

**Comment by darioizzo** [comment]
The population is serialisable, so you can. As the population contains also a problem you problem need to be serialisable too. If thats not the case, the other option is to save to file all chromosomes and then create a population pushing back those chromosomes again in an empty pop. This last method has the problem that it will cause new fitness function evaluations even if those fitnesses were already evaluated!!
