### ISSUE TITLE
Support for general PAGMO2 installation

### ISSUE THREAD

**Issue by SBTheta** [esa/pagmo#195]
Hello,

Is there a more detailed installation guide for PAGMO2 (MAC OS) ? main questions : 
a) when I try to configure IPOPT it complains that it cannot find BLAS, Lapack - but its in the Third Party folder in the IPOPT directory. Does anyone know the the issue here ?
b) Do I still need a working version of Python to install PAGMO2 on a MAC OS ?

Thanks
SB

**Comment by bluescarni** [comment]
I would suggest to use conda for the installation on OSX:

https://esa.github.io/pagmo2/install.html#installation-with-conda

Regarding your specific questions:

- you should probably ask about Ipopt installation in the Ipopt mailing list:

https://list.coin-or.org/pipermail/ipopt/

- you need Python if you want to use pagmo2 from python, if you are using only the C++ parts you do not need Python.

I am closing this as it pertains pagmo2 and this is the pagmo1 bugtracker. Please use the pagmo2 bugtracker for issues regarding pagmo2:

https://github.com/esa/pagmo2/issues
