### ISSUE TITLE
Missing pygmo.problem & pygmo_plugins_nonfree issue

### ISSUE THREAD

**Issue by NigelPB** [esa/pagmo#198]
Hello,

I'm trying to install Pykep and Pygmo on a Mac (OSX 10.13.1) using Anaconda, which I understand (from https://esa.github.io/pagmo2/install.html) is a preferred approach to installing the system. I'm using Anaconda3, and I'm installing into a freshly created environment using the following line:

conda create --name pykep2 python=3.6 boost=1.66 cmake git pykep=2 pygmo=2 scipy matplotlib

This *seems* to work: I can run several of the Pykep examples, getting graphical and numerical outputs matching those discussed on the following page:

https://esa.github.io/pykep/examples/index.html

And since Example 1 uses Pygmo, it seems that at least some aspect of the Pygmo installation has succeeded. However, I can't run all of the examples, and further investigation shows that  pygmo.problem isn't available: the command 

" from pygmo.problem import * "

results in the error   ModuleNotFoundError: No module named 'pygmo.problem' 

I also find it impossible to install pygmo_plugins_nonfree using conda, because of an "Unsatisfiable Error" due to that package requiring boost 1.66.0, while the conda version of Pykep apparently requires Boost 1.65.0.

I think these two issues are preventing the other examples from running. 

Can anyone suggest what I'm doing wrong? Am I being too simplistic about the way Pykep and Pygmo need to be installed via Conda?

Thanks

Nigel

**Comment by NigelPB** [comment]
I'm closing this because one problem has been solved - another remains but I will post as a new issue.

**Comment by darioizzo** [comment]
This old pagmo code is not used anymore, nor maintained. Please open issues on pagmo2 pages if relevant.
