### ISSUE TITLE
Please do not install Eigen headers, it is available on all systems

### ISSUE THREAD

**Issue by yurivict** [esa/pagmo#204]
Please only install ```pagmo``` headers.

**Comment by darioizzo** [comment]
This project is discontinued and no longer maintained. 

Use pagmo2 instead (https://github.com/esa/pagmo2) available in precompiled binaries in conda, pip, homebrew. Note that migration is still not implemented in pagmo2 as well as some of the MO algorithms (list of algorithms is here: https://esa.github.io/pagmo2/docs/algorithm_list.html

**Comment by darioizzo** [comment]
of course, eigen headers are not installed in the new version.
