### ISSUE TITLE
Question: Which method to use for hypervolume calculations

### ISSUE THREAD

**Issue by morecfd** [esa/pagmo#206]
Hi,
Guy, could you please le tme know which method to use to show the convergence of my MOEA model?
I have a saved an archive of all non-dominated solutions for a multi-objective problem. The list have about 6000 rows (number of archived non-dominated solution) and 3 columns (number of objectives).

Thanks

**Comment by darioizzo** [comment]
Please do not use isseus to ask questions on how to solve your particular problem. Issues are for code related suggestions / bug reporting. You can try to ask your question on the pagmo2 user gitter channel ..
