### ISSUE TITLE
type object 'algorithm' has no attribute 'nspso'

### ISSUE THREAD

**Issue by ludohenin** [esa/pagmo#208]
I'm currently trying to play around with PyGMO (awesome work btw) and I'm new to Python.

I've a working conda environment.

Making UDP and population works great, I'm stuck here: 

```py
import pygmo as pg
algo = pg.algorithm.nspso()
# => AttributeError: type object 'algorithm' has no attribute 'nspso'

# Also tryed with the same result
# pg.algorithms.nspso()
# pg.nspso()
```

PSO is loading fine but I've a multi objective problem to solve.

**Comment by darioizzo** [comment]
The code is documented here: https://esa.github.io/pagmo2/ where you will also find some python tutorials that can help you to start quickly.

You can also ask questions in our gitter channel (https://gitter.im/pagmo2/Lobby), where the community will try to help you in case you have coding issues.

As for your question, ```algorithm``` is not a namespace, nor a class with method ```nspso```. The intended usage would then be (check the docs):
```
import pygmo as pg
uda = pg.nspso()
algo = pg.algorithm(uda)
print(algo)
```

**Comment by darioizzo** [comment]
I am closing this since its not an issue, rather a question on the API which is also specifically documented.

**Comment by bluescarni** [comment]
Note also that NSPSO is currently available only in the git version of pagmo2. pagmo 2.12.0, which will contain NSPSO, will be released in a few weeks.
