### ISSUE TITLE
What happened to the pygmo 2.x documentation?

### ISSUE THREAD

**Issue by Nick-Hemenway** [esa/pagmo#211]
I'm currently using pygmo 2.1.12 and I cannot find documentation for it anywhere. I had a few links saved in my code as comments and they no longer work. I don't know how to tell for sure, but I believe the docs contained at: https://esa.github.io/pygmo/ are for version 1.1.7.

**Comment by darioizzo** [comment]
https://esa.github.io/pygmo2/
