### ISSUE TITLE
Get PyGMO into pip

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo#49]
We would like the python 2.7 and python 3 users to be able to install PyGMO (latest release https://github.com/esa/pagmo/releases/latest) using `pip`:

``` bash
$ pip install pygmo
```

This requires a bit of work though as we have boost libraries attached.
Numpy could be doing something similar though (according to Francesco)

**Comment by darioizzo** [comment]
[Python wheels](http://pythonwheels.com/) are a possible solution. It remains to be understood how to deal with boost libraries.

**Comment by pbreach** [comment]
This would be a huge plus. The project itself looks great, but the build process on Windows is a nightmare for those who haven't had to deal with compiling libraries before (living in a Python bubble). I myself am struggling with it and considering alternatives.

**Comment by karthikraman** [comment]
@pbreach One way to get around the Windows build nightmare is to use Anaconda. I created a virtual Python 2.7 env inside of Anaconda, and I was up and running instantaneously.

**Comment by darioizzo** [comment]
Hopefully with the coming PyGMO 2.0 the process will be smoothed ....

**Comment by pbreach** [comment]
@karthikraman I am using Anaconda, but didn't think that conda had all the dependencies and compiled them in the right way for pygmo. Care to share your steps? I would recommend including these in the documentation.

**Comment by karthikraman** [comment]
The steps were fairly simple:
1. Install Anaconda x64 latest 
2. Create a new environment with Python 2.7: `conda create --name python2 python=2.7`
3. Activate the environment: `activate python2`
4. Install PyGMO: `conda install -c ccordoba12 pygmo=1.1.5`

**Comment by willcodeforfudd** [comment]
Has this been implemented?  I managed to (apparently) painlessly install pyGMO by typing
`pip install pygmo`
This reports a success but the sample code from the tutorial:
```
from pygmo import * 
prob = problem.schwefel(dim = 50)
algo = algorithm.de(gen = 500)
isl = island(algo,prob,20)
print (isl.population.champion.f)
isl.evolve(10)
print (isl.population.champion.f)
```
returns:
```
Traceback (most recent call last):
  File "./pyGMO_basic.py", line 2, in <module>
    prob = problem.schwefel(dim = 50)
AttributeError: type object 'problem' has no attribute 'schwefel'
```
Before I attempted to install via pip I got an error at the import line.  Is there something daft that I'm doing?  The source install doesn't worry me, but obviously pip would be super convenient.  The version of pygmo seems to be 2.6

**Comment by darioizzo** [comment]
The new pygmo 2.x was released one year ago and is fully distributed via conda and pip. But the API changed slightly hence you need to get familiar with the new syntax. CHeck the documentation here https://esa.github.io/pagmo2/index.html

What you wrote above is now equivalent to:

```
import pygmo as pg
prob = pg.problem(pg.schwefel(dim = 50))
algo = pg.algorithm(pg.de(gen = 500))
pop = pg.population(prob, 20)
print(population.champion_f)
pop = algo.evolve(pop)
print(population.champion_f)
```

**Comment by willcodeforfudd** [comment]
Superb,  Thanks!  I guess that I was reading the old docs.

minor fix to supplied code as below:
```
import pygmo as pg
prob = pg.problem(pg.schwefel(dim = 50))
algo = pg.algorithm(pg.de(gen = 500))
pop = pg.population(prob, 20)
print(str(pg.population.champion_f))
pop = algo.evolve(pop)
print(str(pg.population.champion_f))
```

**Comment by darioizzo** [comment]
actually no, its
```
import pygmo as pg
prob = pg.problem(pg.schwefel(dim = 50))
algo = pg.algorithm(pg.de(gen = 500))
pop = pg.population(prob, 20)
print(pop.champion_f)
pop = algo.evolve(pop)
print(pop.champion_f)
```

**Comment by darioizzo** [comment]
otherwise you get the method :)

**Comment by willcodeforfudd** [comment]
Ah... yes - that looks a bit better.  I had wondered if the object reference was relevant.

Thanks again. :-)

**Comment by darioizzo** [comment]
I will close this old ticket as it is not relevant anymore pygmo2 is in conda and pip and PyGMO 1.x support is discontinued.
