### ISSUE TITLE
Linking with Boost librarie

### ISSUE THREAD

**Issue by ghost** [esa/pagmo#69]
Ubuntu 14.04.
x64
Using libboost1.55

At [49%] Built target pagmo_static
Linking CXX executable main"

I start getting a lot of undefined references to boost library things.  

"In function pagmo::detail::get_current_thread_data()"
... "undefined reference to boost::this_thread::interruption_point()"
... "boost::thread::detatch"
... "boost::thread::XX"
etc.

I checked.  libboost-thread1.55-dev 
is installed via apt-get.

It seems that in the Ubuntu repositories, there are two variants of boost. There is 1.54 and 1.55.  I installed the latter.

**Comment by steven-varga** [comment]
Thank you! above advice worked for me on LINUX MINT 17 ID-d below with 
-------------------------------------------------------
pagmo TAG: 1.1.7-2-g140296f
Date:   Sat Jul 4 18:49:27 2015 +0200
-------------------------------------------------------

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
cat: /etc/upstream-release: Is a directory

**Comment by MJDiaz89** [comment]
`This is a known behavior in Ubuntu and its related to some change that
Canonical must have introduced in the gnu toolset.

Easy workaround is to change the order of linking. First the static then
the mandatory. Relevant file is
https://github.com/esa/pagmo/blob/master/CMakeLists.txt
line 424. Just put

TARGET_LINK_LIBRARIES (main pagmo_static ${MANDATORY_LIBRARIES} )

And the same for examples and tests in case you need them

Dario`

@darioizzo , where would this go now with the newer version of the CMakeLists.txt file?  I'm having the same issues on Ubuntu 16.04 running gcc 5.4.0.
