### ISSUE TITLE
PyGMO -- Pickling error at evolve

### ISSUE THREAD

**Issue by e-dub** [esa/pagmo#97]
I am currently integrating PyGMO into an existing optimization routine in which the system being optimized is defined and from which the optimizer is called. I am using V1.1.5 with Python 2.7.6 on a Ubuntu 14.04 machine in a 64-bit architecture.

When doing so I get the following error:

        Traceback (most recent call last):
          File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
            send(obj)
        PicklingError: Can't pickle <class 'OptRoutine.OptSysEq'>: attribute lookup OptRoutine.OptSysEq failed

Any ideas on how I can solve this?

Thanks in advance! 

Below is a minimalistic code of how this is called: 

TestProb.py -- The test problem to be optimized, including optimization call:
 
        import numpy as np
        from scipy.optimize import rosen
        from OptRoutine import Opt

        def SysEq(x, gc):
             return(rosen(x), [])

        Alg = "PyGMO_de"
        x0 = np.zeros([2, ])
        xL = np.ones([2, ])*-5
        xU = np.ones([2, ])*5
        gc = []
        fOpt, xOpt = Opt(SysEq, Alg, x0, xL, xU, gc)

OptRoutine.py -- The optimization routine 

        import PyGMO
        from PyGMO.problem import base
        import numpy as np

        def Opt(SysEq, Alg, x0, xL, xU, gc):
            class OptSysEq(base):
                def __init__(self, dim=2):
                    super(OptSysEq, self).__init__(dim)
                    self.set_bounds(xL, xU)
                    self.__dim = np.size(x0)

                def _objfun_impl(self, x):
                    f, g = SysEq(x, gc)
                    return(f,)
            ngen = 20
            nindiv = 60
            dim = np.size(x0)
            prob = OptSysEq(dim=dim)
            algo = PyGMO.algorithm.de(gen=ngen, f=0.8, cr=0.9, variant=2,
                                      ftol=1e-06, xtol=1e-06, screen_output=False)
            isl = PyGMO.island(algo, prob, nindiv)
            isl.evolve(1)
            isl.join()
            xOpt = isl.population.champion.x
            fOpt = isl.population.champion.f[0]
            return(fOpt, xOpt)

**Comment by darioizzo** [comment]
My guess that your code is invalid for pickle (similarly to http://stackoverflow.com/questions/4677012/python-cant-pickle-type-x-attribute-lookup-failed).

Try not to not encapsulate OptSysEq in the routine Opt. Just put it outside and upon construction assign the variable gc do some data member then used in the obj fun. 

Let us know.

**Comment by e-dub** [comment]
Thanks for the tip Dario! Worked like a charm. 

Here is the solution:

TestProb.py unchanged.

OptRoutine.py now:

```python
import PyGMO
from PyGMO.problem import base
import numpy as np


class OptSysEq(base):
    def __init__(self, SysEq=None, xL=0.0, xU=2.0,  gc=[], dim=1):
        super(OptSysEq, self).__init__(dim)
        self.set_bounds(xL, xU)
        self.__dim = dim
        self.gc = gc
        self.SysEq = SysEq

    def _objfun_impl(self, x):
        f, g = self.SysEq(x, self.gc)
        return(f,)


def Opt(SysEq, Alg, x0, xL, xU, gc):
    ngen = 500
    nindiv = 40
    dim = np.size(x0)
    prob = OptSysEq(SysEq=SysEq, xL=xL, xU=xU, gc=gc, dim=dim)
    if Alg is "PyGMO_de":
        algo = PyGMO.algorithm.de(gen=ngen, f=1, cr=1, variant=2,
                                  ftol=1e-03, xtol=1e-03, screen_output=False)
    isl = PyGMO.island(algo, prob, nindiv)
    isl.evolve(1)
    isl.join()
    xOpt = isl.population.champion.x
    fOpt = isl.population.champion.f[0]
    nEval = isl.population.problem.fevals
    return fOpt, xOpt
```
